services:

  proxy:
    image: nginx:1.25
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - frontend-network
      - backend-network
    restart: unless-stopped

  frontend:
    image: welannn/urban-ko-admin:${BACK_VERSION_TAG}
    pull_policy: always
    container_name: admin-front-uko
    expose:
      - "8080"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - frontend-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  backend:
    image: ayriko/urban-ko-back:${BACK_VERSION_TAG}
    pull_policy: always
    container_name: backend-uko
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${BACK_PORT}
      CORS_ORIGIN: ${CORS_ORIGIN}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - ${BACK_PORT}
    networks:
      - backend-network
    user: '1000:1000'
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${BACK_PORT}/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 30s

  mongodb:
    image: mongo:7
    container_name: mongodb-uko
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - backend-network
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  mongo-express:
    profiles:
      - ${ENABLE_MONGO_EXPRESS}
    image: mongo-express:1
    container_name: mongo-express-uko
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_BASIC_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_BASIC_PASSWORD}
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    networks:
      - backend-network
    command: >
      sh -c "
        echo 'Waiting for MongoDB...' &&
        until nc -z mongodb 27017; do sleep 2; done &&
        echo 'MongoDB is up! Starting Mongo Express...' &&
        node app
      "

volumes:
  mongo_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
